server:
  servlet:
    context-path: /
  port: ${SERVER_PORT:8000}

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 500ms
      percentiles-histogram:
        "[http.server.requests]": true

spring:
  application:
    name: arch-documentgenerator
  main:
    banner-mode: off

logging:
  level:
    root: INFO
    org.springframework: INFO
    ru.gur.arch: INFO

app:
  minio:
    accessKey: ${MINIO_ACCESS_KEY:minio_access_key}
    secretKey: ${MINIO_SECRET_KEY:minio_secret_key}
    url: ${MINIO_URL:http://arch.homework:30002}
    bucketName: agreementbucket