server:
  servlet:
    context-path: /
  # http://localhost:8080/swagger-ui.html
  port: 8082

management:
  server:
    port: 8002
  endpoints:
    web:
      base-path: /

logging:
  level:
    root: INFO
    org.springframework: INFO
    ru.gur.arch: DEBUG

app:
  minio:
    accessKey: minio_access_key
    secretKey: minio_secret_key
    url: http://localhost:9000
    bucketName: agreementbucket